// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AcmeHero } from "./components/navbar/page";
// import { Footer7 } from "./components/Footer/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         {/* <AcmeHero/> */}
//         {children}
//         <Footer7/>
//         </body>
//     </html>
//   );
// }











import { Inter } from "next/font/google";
import "./globals.css";
import  AcmeHero  from "./components/navbar/Navbar"; // Navbar layout path link
import { Footer7 } from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Comfort by Stowave",
  description: "An interactive tapestry of light and motion",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-black dark:bg-white`}>
        
        {/* 1. Global Fixed Layer Container — Yeh ab har page par bilkul top par layer karega */}
        <div className="fixed top-0 left-0 w-full z-50 pointer-events-auto">
          <AcmeHero/>
        </div>

        {/* 2. Page Content Render Area */}
        <main className="relative min-h-screen">
          {children}
          <Footer7/>
        </main>

      </body>
    </html>
  );
}
